author = "Hashed"
description = "Louise W. Reed is a Certified Public Accountant in Richmond Virginia specializing in working with Small Businesses, Entrepreneurs and individuals looking to realize their dreams through tax and accounting opportunities. The firm works in a paperless environment. Louise is a QuickBooks ProAdvisor."

[hero]
  title = "Creating a real-time marketplace for transferable tax credits…Afloat, Inc."
  img = "images/hero_bg.jpg"


[nav]
  us = "Us"
  contact = "Contact"
  resources = "Client Resources"

[us]
  enable = true

[resources]
  title = "Client Resources"
  enable = true
  [[resources.resource]]
    title = "Internal Revenue Service"
    img = "resources/irs.gif"
    link = "https://www.irs.gov/"
  [[resources.resource]]
    title = "Electronic Federal Tax Payment System"
    img = "resources/eftps.gif"
    link = "https://www.eftps.com/eftps/"
  [[resources.resource]]
    title = "NC Department of Revenue"
    img = "resources/ncdr.gif"
    link = "https://www.ncdor.gov/"
  [[resources.resource]]
    title = "VA Dept of Revenue - For Businesses"
    img = "resources/drb.gif"
    link = "https://www.business.tax.virginia.gov/VTOL/tax/Login.xhtml"
  [[resources.resource]]
    title = "VA Dept of Revenue - For Individuals"
    img = "resources/dri.gif"
    link = "https://www.individual.tax.virginia.gov/IOP"

[contact]
  enable = true
  title = "Contact"

[footer]
  enable = true
  note = "<p><small>&copy;  2009-2020 Louise W. Reed, CPA, PC. <br> <a href='mailto:louise@stayafloat.io'>louise@stayafloat.io</a>"